nelmio_cors:
    defaults:
        allow_origin: ['*'] # autorise toutes les origines
        allow_methods: ['GET'] # autorise toutes les méthodes
        allow_headers: ['*'] # autorise tous les headers
        expose_headers: ['Link'] # autorise tous les headers à être exposés
        max_age: 3600 # autorise le cache pendant 1 heure
    paths:
        '^/api/': null
        '^/': null
